### ISSUE TITLE
Clean up `no-throw-literal` warning

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#108]
There may be code that depends on literals being thrown.  Discuss this in Slack before implementing it.

```js
// Before
if (foo) {
  throw t + " error";
}

// After
if (foo) {
  throw new Error(

**Comment by GoodForOneFare** [comment]
May be possible to do this as a lint rule fix.  Discuss with Chris before starting on this.

**Comment by lemonmade** [comment]
Not enough of these to warrant an extra codemod.
