### ISSUE TITLE
Remove unnecessary IIFEs from non-test code

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#113]
There's a few [IIFEs](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression) that don't seem to serve any purpose, e.g., in `finances-report.js`:

```javascript
_getColumnIndexByKey(result, key) {
  if (!key) {
    return;
  }

  return (() => {
    for (let [index, each] of result.columns.entries()) {
      const column = result.columns[index];

      if (column.field === key) {
        return index;
      }
    }
  })();
}
```

A non-exhaustive list of IIFEs follow.  Note that some of these may be necessary; watch out for switches or loops with return values: 

* `CachedResourceSearch#_precompileTemplates`
* `EditLinkModal#createLink`
* `HumanizedDatepicker#selectRange`
* `IFrameMessageHandler#handleMessage`
* `InventoryColumn#updateInventory`
* `MixedContentProtection#parseAndSerialize`
* `MixedContentProtection#attrFromTagName`
* `ProductOptions#findFirstAvailableName`
* `ProductVariantOptions#renderOptionRows`
* `ShippingZoneProvinceTagDisplay#addProvince`
* `SKUGenerator#setSKU`
* `SpreadsheetNavigator#applyMultiEdit`
* `Taggable#findFormObject`
* `UIChoiceList#initializeSubchoices`.
* `VariantImageActions#uploadComplete`

**Comment by GoodForOneFare** [comment]
`shopify-codemod/transform/removeUselessReturnFromTest` contains an `isUselessIIFE` method that *may* be useful for this.

**Comment by GoodForOneFare** [comment]
Possibly fixed by mainline decaf merge.  Please don't start work on this until we've finished evaluation.

**Comment by lemonmade** [comment]
Did decaf merge fix this @GoodForOneFare?

**Comment by GoodForOneFare** [comment]
@lemonmade  It definitely helped, and there's a couple that I can fix with a trivial change to `decaf`.  Once I've done that, I'll update this issue with anything that remains.

**Comment by GoodForOneFare** [comment]
My fix for `try/catch` IIFEs was accepted into mainline decaf.  Doing the same for `for` loops turned out to be non-trivial. The number of IIFEs has greatly decreased, and I think that's good enough for now.
