### ISSUE TITLE
Discuss `shopify/shopify` globals

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#118]
What are we going to do with `Shopify`?  From what [I've read about static modules](https://medium.com/@kentcdodds/misunderstanding-es6-modules-upgrading-babel-tears-and-a-solution-ad2d5ab93ce0#.6b6segvcq), assigning values to a pure ES module isn't valid.

Which of these can be used as `import`s?
* Aviary
* Bindings
* Bugsnag
* intuit
* measurement
* Mousetrap
* Page
* QRCode
* Reportify
* SafeLocalStorage
* Shopify
* Stripe
* tinymce
* Trix
* TurboGraft
* Turbolinks
* Twine"

**Comment by lemonmade** [comment]
Any global that is setup up by something in our node_modules should work fine as an import, so long as we add it to the `globals` option of commoner. Globals set up in other ways will probably need to just use the global, no import, and we can add those to the ESLint config. Things we set up ourselves (`Shopify` being the main one). Can continue to be set in an early script, and the `expose` directive in commoner will take care of augmenting that with anything else we want to expose globally.

**Comment by lemonmade** [comment]
I don't think there's really anything wrong with assigning to `Shopify` if what it exports is just a regular object. It's gross because we are mutating things we shouldn't be, but pretty sure there's no problem with it in terms of the module spec.
