### ISSUE TITLE
Manually convert require .coffee files to .js with imports

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#122]
The following files compile down to 0 byte `.js` files because they're full of Sprockets directives:
* `app/assets/javascripts/admin/modules/rte.coffee`
* `app/assets/javascripts/admin.coffee`
* `app/assets/javascripts/design_mode_next/index.coffee`
* `app/assets/javascripts/external/app.coffee`
* `app/assets/javascripts/partners/partners-vendor.coffee`
* `app/assets/javascripts/partners.coffee`
* `app/assets/javascripts/services_internal/services-internal.coffee`
* `app/assets/javascripts/subscription.coffee`

**Comment by lemonmade** [comment]
We will have to be careful of **any** file that uses sprockets directives, since these will be stripped out. This would be good guidance to include in the `esify` README.

**Comment by GoodForOneFare** [comment]
Added the Sprockets directive stripping to #121.
