### ISSUE TITLE
Consider more transforms to address lint errors

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#123]
| Error | Count | Github Issue |
|-------|---------|----|
| no-undef    | 1082 | |
| no-return-assign    | 440 | #104 |
| no-this-before-super    | 432 | #69 |
| no-undefined    | 256 | |
| arrow-body-style    | 214 | |
| no-shadow   | 213 | |
| no-var  | 193 | |
| no-use-before-define    | 144 | |
| prefer-arrow-callback   | 93 | |
| import/no-duplicates    | 74 | #99 (partial solution) |
| prefer-rest-params  | 68 | |
| no-duplicate-imports    | 52 | #99 (partial solution) |
| no-redeclare    | 50 | |
| no-cond-assign  | 39 | #103 |
| no-void | 39 | |
| radix   | 33 | #117 |
| no-unreachable  | 18 | |
| no-undef-init   | 14 | |
| no-catch-shadow | 13 | |
| no-self-assign  | 13 | |
| no-shadow-restricted-names  | 13 | |
| shopify/no-fully-static-classes | 10 | |
| babel/new-cap   | 9 | |
| no-case-declarations    | 9 | |
| no-native-reassign  | 6 | |
| prefer-spread   | 6 | |
| array-callback-return   | 4 | |
| no-loop-func    | 4 | |
| no-useless-escape   | 4 | |
| lodash/unwrap   | 1 | |
| no-eval | 1 | |
| no-new-func | 1 | |
| no-unmodified-loop-condition    | 1 | |
| promise/always-return   | 1 | |

**Comment by lemonmade** [comment]
I'm going to close this since we have addressed about as much of this as I think we reasonably can.
