### ISSUE TITLE
Consider more transforms to address lint warnings

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#124]
| Warning | Count | Github Issue |
|--------|-----------|-----------|
| camelcase | 1267 | |
| eol-last  | 819 | Autofix by eslint #68 |
| sort-class-members/sort-class-members | 739 | |
| no-unused-vars  | 654 | |
| consistent-return | 633 | |
| babel/arrow-parens  | 529 | |
| prefer-const  | 382 | #137 |
| dot-notation  | 312 | #111 |
| shopify/jquery-dollar-sign-reference  | 196 | #107 (partial fix) |
| no-empty-function | 178 | #110 (partial fix) |
| shopify/prefer-class-properties | 166 | |
| newline-per-chained-call  | 152 | |
| id-length | 141 | |
| block-scoped-var  | 124 | |
| no-unused-expressions | 95 | |
| lodash/prop-shorthand | 71 | |
| func-style  | 62 | |
| lodash/preferred-alias  | 54 | |
| shopify/binary-assignment-parens  | 48 | |
| no-implicit-coercion  | 44 | #105 |
| consistent-this | 34 | |
| shopify/prefer-early-return | 32 | |
| quotes  | 27 | |
| no-extra-semi | 21 | |
| lodash/collection-method-value  | 20 | |
| no-console  | 16 | |
| no-empty  | 14 | #109 (partial fix) |
| lodash/chain-style  | 13 | |
| prefer-template | 9 | |
| no-sequences  | 8 | |
| shopify/sinon-prefer-meaningful-assertions  | 8 | #81 |
| lodash/no-single-chain  | 6 | |
| yoda  | 6 | |
| comma-dangle  | 5 | |
| no-new  | 5 | |
| promise/catch-or-return | 5 | |
| babel/object-shorthand  | 3 | |
| no-nested-ternary | 3 | |
| no-alert  | 2 | |
| no-extra-boolean-cast | 2 | |
| no-inner-declarations | 2 | |
| no-throw-literal  | 2 | |
| operator-assignment | 2 | |
| lodash/matches-shorthand  | 1 | |
| lodash/prefer-flat-map  | 1 | |
| space-infix-ops | 1 | |

**Comment by lemonmade** [comment]
I definitely want to solve the prefer `const`, particularly for `for of` loops, which appear to consistently use `let`.

**Comment by fandy** [comment]
I can work on a prefer `const` in `for of` when no reassignment in scope transform.

**Comment by lemonmade** [comment]
@fandy no need, I corrected it in the `jscodemod/no-vars` transform, it should be available for us to use.

**Comment by lemonmade** [comment]
I'm going to close this because I think we've addressed about as many of these as we can.
