### ISSUE TITLE
Fix files that define multiple classes

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#125]
`kpi.coffee` defines ~10 classes.  This causes dependent classes to import the same file multiple times (see below).

Not sure what the solution is.  Should commoner be turning these into separate exports, and importing specific names, or should we manually break files down into single classes?

From `ChannelOnlineDashboard`:
```js
import KpiConversionPurchased from 'admin/modules/dashboard/kpi';
import KpiConversionCheckout from 'admin/modules/dashboard/kpi';
import KpiConversionCart from 'admin/modules/dashboard/kpi';
import KpiUniqueVisitors from 'admin/modules/dashboard/kpi';
import KpiVisitors from 'admin/modules/dashboard/kpi';
import KpiMultiTime from 'admin/modules/dashboard/kpi_multi_time';
```

**Comment by lemonmade** [comment]
Lets move the classes into separate files.
