### ISSUE TITLE
Files that mix `$` and `jQuery` try to `import 'jquery'` twice

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#126]
Files like `skip-link.coffee` reference `jQuery`/`$`, which generates duplicate `import` statements.
```
$(document).on('keydown', '.js-btn-skip', evt => {
  if (evt.keyCode === jQuery.ui.keyCode.ENTER) {
```

`combobox` is a special case that ends up with 3 jQuery definitions.

```js
import jQuery from 'jquery';
import $ from 'jquery';
// ...SNIP...
const $ = jQuery;
```

**Comment by lemonmade** [comment]
What do you think the correct solution is here? I'm thinking maybe an earlier transform to rename `jQuery` to `$` and a special fix for `combobox`, but open to suggestions.

**Comment by GoodForOneFare** [comment]
Yes, exactly that.  There's way more instances of `$` in core, and there shouldn't be any difference in behaviour between `$`/`jQuery`.
