### ISSUE TITLE
Fix more `prefer-const` warnings

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#137]
The `js-codemod/no-vars` transform should be picking these off, but there are many left behind in places that should use `const`.

For example, in `product-resource-browser.js`, this loop should use a `const` for the `variant` variable in its `for` loop:
```js
for (let variant of product.variants) {
  variant.disabled = this._variantDisabled(variant, product);
  variant.alreadyAdded = this._variantSelected(variant);

  if ((product.alreadyAdded === null || product.alreadyAdded) && !variant.disabled) {
    product.alreadyAdded = variant.alreadyAdded;
  }
}
```

**Comment by lemonmade** [comment]
I have noticed this mostly in `for of` loops, I think there must be some logic off in the transform we use for this specific case.

**Comment by lemonmade** [comment]
Fix submitted to `js-codemod`: https://github.com/cpojer/js-codemod/pull/43
