### ISSUE TITLE
Verify that ranges/slices are still accurate

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#160]
Before merging in mainline decaf, I recall seeing some off-by-one changes in transformed ranges.  I'm not sure whether before/after was correct, so I should check that, eh?

**Comment by lemonmade** [comment]
Do you mean that decaf is creating off-by-one ranges, or that our transform is messing things up?

**Comment by GoodForOneFare** [comment]
Decaf.

**Comment by GoodForOneFare** [comment]
#170 contains a few edge cases that'll have to be fixed.
