### ISSUE TITLE
esify may be causing resource exhaustion

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#162]
While running the `esify@12.2.0`, zsh stops functioning with `fork failed: resource temporarily unavailable`, and Atom can't to open new windows.

Eyeballing recent changes, I'm guessing `runESLint` and/or `findESLintBinary` is opening more file descriptors than anticipated.

(Or I could be completely wrong, and I just have to reboot my computer :/ )

**Comment by GoodForOneFare** [comment]
Commented out `runESLint` and things are speedy again.  If the binary can be looked up once then reused, I think things'll improve.

@lemonmade is programmatically calling eslint+fix without `proc.exec` possible?

**Comment by lemonmade** [comment]
Totally possible, I will look into it.
