### ISSUE TITLE
Add parens to single-parameter arrow functions

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#167]
Our linting config will carp about [arrow-parens](http://eslint.org/docs/rules/arrow-parens) if they're omitted.

``` js
foo.then(bar => qux());
```

should become:

``` js
foo.then((bar) => qux());
```

**Comment by GoodForOneFare** [comment]
Will be fixed if this `recast` PR is accepted: https://github.com/benjamn/recast/pull/288.

**Comment by lemonmade** [comment]
The PR to recast is good, but does the ESLint run not fix this?

**Comment by GoodForOneFare** [comment]
You'd think, but I don't see any `fix` text in https://github.com/eslint/eslint/blob/master/lib/rules/arrow-parens.js.  A quick 🎩 with eslint -fix enabled added a newline, but didn't tweak function params.

**Comment by GoodForOneFare** [comment]
Fix has been merged into Recast.  I'll update our config.
