### ISSUE TITLE
eslint not being installed by setup script

### ISSUE THREAD

**Issue by justinthec** [Shopify/javascript#174]
```sh
npm run setup
```
results in 
```sh
npm WARN eslint-plugin-shopify@12.0.1 requires a peer of eslint@~2.10.0 but none was installed.
```

In addition running `npm install eslint` fails to install it as well.

@lemonmade

**Comment by lemonmade** [comment]
@justinthec when you get a chance, can you try setting up again? It still runs fine for me :(
