### ISSUE TITLE
ESLint is not actually running

### ISSUE THREAD

**Issue by lemonmade** [Shopify/javascript#185]
My fix to ESLint broke it. Trying to do the right thing locally results in some crazy require-related errors, which I think relate to the babel stuff we do in `shopify-codemod`.

**Comment by GoodForOneFare** [comment]
Is eslint doing anything other than appending a newline?  Can we remove eslint and append EOF newlines if that transformed JS doesn't have one?

**Comment by lemonmade** [comment]
There are a bunch of other fixes, not sure how much they are getting us but I think they are worth having.
