### ISSUE TITLE
No way to create an object with underscored keys

### ISSUE THREAD

**Issue by bouk** [Shopify/javascript#209]
With our current eslint rules, there's no way to do 

```
a = JSON.stringify({
  some_prop: 1
});
```

because we need all identifiers to be camelcase. We could set http://eslint.org/docs/rules/camelcase to `{ "properties": "never" }`, but that would make it legal to have underscored properties in classes too. 

We could tell people to just ignore the rule selectively, but that's kind of gross and defeats the purpose

what do??

@lemonmade @matthelm

**Comment by lemonmade** [comment]
So, for me, the worst case is that you can write object literals or classes that have snake cased keys when they don't actually need to be snake cased. The only way I can think of to allow it when needed is to recommend wrapping the offending objects in `eslint-enable/-disable camelcase`. It's a little gross, but it gets the job done, and if it is a common occurrence it's probably a reasonable compromise to have a single utility that "ruby-fies" passed object literals so they can be camelcase everywhere.

**Comment by matthelm** [comment]
Did some quick digging, and Chris's suggestion seems to be the recommended way to go https://github.com/eslint/eslint/issues/1550#issuecomment-65846342
