### ISSUE TITLE
Can't use babel-preset-shopify with rollup

### ISSUE THREAD

**Issue by bouk** [Shopify/javascript#212]
Rollup [needs to have the commonjs plugin disabled](https://github.com/rollup/rollup-plugin-babel#modules) which is currently not possible in our preset

**Comment by lemonmade** [comment]
The ES2015 preset now accepts a `{modules: false}` option to disable transpiling `import`/ `export`s. We should turn our preset into a function that accepts the same option and just passes it along to that preset.

**Comment by lemonmade** [comment]
If anyone else is doing this, here is the file that details the change that happened in Babel 6.13.0 that we can use: https://github.com/babel/babel/blob/master/packages/babel-preset-es2015/src/index.js

**Comment by lemonmade** [comment]
Should be solved now by passing `{modules: false}` to the `shopify/web` preset.
