### ISSUE TITLE
Setup greenkeeper with eslint-plugin-shopify

### ISSUE THREAD

**Issue by mikkoh** [Shopify/javascript#213]
`eslint-plugin-shopify` has a peer dependency for `eslint` 3.3.x. The current version is at 3.4.x. It would be nice to have `greenkeeper` create Pull Requests to get updates for peer deps or locked modules. It's safe to do this... Although the way that this repo is setup as a mono package might cause issues with `greenkeeper`

**Comment by lemonmade** [comment]
I'm open to doing it, but I have a somewhat workable system of just going through every few weeks, bumping the versions on all the ESLint/ plugin dependencies, and adding configuration for all new rules as I do that.

**Comment by GoodForOneFare** [comment]
Reraised [in the eslint-plugin-shopify repo](https://github.com/Shopify/eslint-plugin-shopify/issues/10).
