### ISSUE TITLE
Look at adding a few more ESLint plugins

### ISSUE THREAD

**Issue by lemonmade** [Shopify/javascript#223]
https://github.com/sindresorhus/eslint-plugin-unicorn
https://github.com/apollostack/eslint-plugin-graphql
https://github.com/jhusain/eslint-plugin-immutable
https://www.npmjs.com/package/eslint-plugin-no-loops

**Comment by GoodForOneFare** [comment]
Reraised here: https://github.com/Shopify/eslint-plugin-shopify/issues/9
