### ISSUE TITLE
Add ESLint config validation tests

### ISSUE THREAD

**Issue by lemonmade** [Shopify/javascript#224]
https://github.com/scottnonnenberg/eslint-config-thehelp/blob/3eaed6cda4e14c10df6609885361776c28691a70/scripts/validate.js#L5-L11

The whole repo is also an interesting look at setting up a custom config.

**Comment by GoodForOneFare** [comment]
Reraised here: https://github.com/Shopify/eslint-plugin-shopify/issues/8
