### ISSUE TITLE
Cannot find `eslint-plugin-mocha` on older versions of Node

### ISSUE THREAD

**Issue by mikkoh** [Shopify/javascript#226]
Sorry I wish I could be more detailed with this Issue.

But @minasmart and I have encountered it where in CI `eslint` simply can't find `eslint-plugin-mocha` when using `plugin:shopify/mocha`. Upgrading Node version seems to fix this issue.

Maybe @minasmart has a repo that is failing in CI currently to give more details.

**Comment by minasmart** [comment]
I have a couple repos that failed with circle's default not version (around 5.7). Doing a rebuild without cache and updating to 6 fixes it.

But any projects we want support for node LTS, this is still an issue.

**Comment by lemonmade** [comment]
Do you have an example of a failed CI run? Do the other configs work correctly? The only thing I can think of is that version 2 of npm is being used, as we depend on the flat structure of version 3 to prevent you from having to manually install all the plugins that are being used.

**Comment by mikkoh** [comment]
@lemonmade here's an old test where it's failing
https://circleci.com/gh/Shopify/get-project-version/2

Here's the source for the commit when it was failing
https://github.com/Shopify/get-project-version/tree/9d7b68d8f995031e37ec6f0720b21f7e1f87376f

**Comment by lemonmade** [comment]
Looks like that build uses npm 2.15.9, which doesn't provide the flat modules structure that the plugin depends on. Not the best solution, but you can force it to use a suitable npm version as part of your circle config: https://github.com/Shopify/javascript/blob/master/circle.yml#L8.

Thoughts? Does changing the version of npm being used not work for other reasons?

**Comment by minasmart** [comment]
It may be worthwhile to add npm3, to the module generator? So at least, new projects don't stumble in the same way.

**Comment by mikkoh** [comment]
Hmmmm.. Could def add that to `circle.yml`. 

But what about users locally testing? Should we add in an `.nvmrc` file? Detect npm version and throw errors?

**Comment by lemonmade** [comment]
In general, I think it's better to have projects pin to a recent version of Node/ npm (or just using yarn :D) via a `.nvmrc`. We should probably also add `dev` support to the boilerplate so that `dev` can do the work of automatically setting the correct node version (not sure if that is done via the `.nvmrc` or `dev.yml`).

**Comment by mikkoh** [comment]
@lemonmade I've upgraded the Node version for the module generator.

https://github.com/Shopify/shopify-module-generator/pull/15

I wonder if we could check the `npm` version in the Shopify eslint plugins? This would give better feedback to developers.

**Comment by lemonmade** [comment]
I'm not sure whether we will be able to do very much, even if we know the npm version, given that we are relying on ESLint's resolution of our configs. It might be possible to provide the actual modules for plugins in our configs, instead of what we currently do (strings that indicate the plugin name), but I actually don't know if that's supported.

**Comment by mikkoh** [comment]
Hmmm. Thats tough cause you might over bundle modules. For instance:

```
    "plugin:shopify/esnext",
    "plugin:shopify/lodash",
    "plugin:shopify/mocha"
```

I never use `lodash` should it be included in a module?

**Comment by lemonmade** [comment]
We always bundle all of the possible plugins since they are small and the cost of downloading all of them is small compared to the configuration hell of needing to install each plugin individually.
