### ISSUE TITLE
Fix this destructuring

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#238]
```coffeescript
{@foo, @bar} = options
```

becomes

```js
this.foo = options.foo, this.bar = options.bar, options;
```

(Actual example is in `product_options_edit.coffee`'s constructor)

**Comment by GoodForOneFare** [comment]
I was misreading the eslint output.  It's ugly, but valid.  esify is deleting this line entirely, but Tyler's warning PR will help with that.

Since I'm already looking at the decaf code, I'll see if it can be quickly improved.

**Comment by GoodForOneFare** [comment]
This is generated by fallback code (https://github.com/Shopify/decaf/blob/master/src/parser.js#L1694)
```javascript
  if (any(props, {this: true})) {
    return fallback(node, meta);
  }
```

i.e., returning the source of destructuring is Coffee's behaviour, and removing that could change a return expression's behaviour :/

@lemonmade are you okay with leaning on Tyler's _removed code_ warning to work around this?

**Comment by lemonmade** [comment]
Why is the line being removed entirely? Shouldn't our transform only remove part of a sequence if that's where the unused expression appears?

I am OK with relying on the warning if the extra effort to improve the codemod is high.

**Comment by GoodForOneFare** [comment]
Because `SequenceExpression` doesn't pass the [isValidExpression](https://github.com/Shopify/javascript/blob/master/packages/shopify-codemod/transforms/remove-unused-expressions.js#L15) check.

I'll put up a PR to make this nicer once I've got the workflow docs done.

**Comment by GoodForOneFare** [comment]
Worked around by adding a new transform in #242.
