### ISSUE TITLE
[babel-preset-shopify] inline environment variables opt in

### ISSUE THREAD

**Issue by macdonaldr93** [Shopify/javascript#252]
Working a project where I don't want `process.env` to be automatically transformed into value. Due to `babel-plugin-transform-inline-environment-variables`, my environment variables are getting transformed to `undefined`.

https://github.com/Shopify/javascript/blob/master/packages/babel-preset-shopify/non-standard-features.js#L7

**Comment by GoodForOneFare** [comment]
Reraised in the new [babel-preset-shopify repo](https://github.com/Shopify/babel-preset-shopify/issues/3)
