### ISSUE TITLE
Can this be used if I want to write custom JS for my shopify theme?

### ISSUE THREAD

**Issue by mdunbavan** [Shopify/javascript#259]
Hi,

I have been using VueJs in my shopify dev and so far it been great but I have hit a blocker where I need to import some JS into my main JS controller file for routing instances and methods, the import cannot be found when I try and render it out on my theme it says 'import is invalid' which means the syntax is not recognised. I have looked at Babel but its complex with shopify and gulp and its too much configuration for my Vue Js work.

All I need to know is can I use it to write my components for my shopify theme?

Thanks

**Comment by lemonmade** [comment]
Sorry @mdunbavan, this repo really just documents our JavaScript styleguide, it does not provide any tooling for compiling/ bundling JavaScript, which it sounds like you are looking for. Unfortunately, you will have to use a bundler, like Webpack, Browserify, or Gulp, along with Babel (to compile your JavaScript to something that the browser understands).
