### ISSUE TITLE
Definition for rule 'jsx-a11y/img-has-alt' was not found

### ISSUE THREAD

**Issue by skew202** [Shopify/javascript#261]
After upgrading from 4.0.1 to 5.0.0 the following eslint error occurred:

`Definition for rule 'jsx-a11y/img-has-alt' was not found  jsx-a11y/img-has-alt`

Cheers

**Comment by GoodForOneFare** [comment]
@ismail-syed can you take a look, please?

**Comment by ismail-syed** [comment]
Thanks @skew202, for raising this issue. We'll be pushing out an update that will address this issue, within the next couple days.

**Comment by ismail-syed** [comment]
This should now be resolved with the `v16.0.0` release of [`eslint-plugin-shopify`](https://www.npmjs.com/package/eslint-plugin-shopify)
