### ISSUE TITLE
Consider adopting prettier

### ISSUE THREAD

**Issue by davidcornu** [Shopify/javascript#262]
https://github.com/prettier/prettier has a lot more details. 

It's been adopted by [quite](https://github.com/yarnpkg/yarn/pull/3401) [a few](https://github.com/facebook/react/pull/9101) [projects](https://github.com/babel/babel/pull/5412) as the de facto style guide (ie. run your code through it and call it a day - similar to [`gofmt`](https://golang.org/cmd/gofmt/)).

With a few configuration options

```shell
prettier --trailing-comma=es5 --single-quote --no-bracket-spacing
```

the output comes pretty close to our ESLint rules. 

The biggest offender I've found so far is we prefer 

```js
(arg) => { /* ... */ }
``` 

over 

```
arg => { /* ... */ }
``` 

for lambdas that take a single argument.

**Comment by lemonmade** [comment]
Yeah, I would love to recommend this, I'm willing to relent on the single param functions (even though it's a terrible choice). We had been waiting on that rule, and on full TypeScript support, before jumping on it, and now that TS is in it seems reasonable. What do you think we'd need to do here to make this a clear recommendation? Instructions on how to use it with the linter? Recommended options? An examples use of it in core?

**Comment by davidcornu** [comment]
> What do you think we'd need to do here to make this a clear recommendation? Instructions on how to use it with the linter? Recommended options? An examples use of it in core?

As far as I can tell, most projects that have adopted it go through a process along the lines of

1. Update ESLint rules to be compatible with Prettier
1. Add a `yarn run prettier` that formats everything with the preferred options
1. Convert the entire code base in one fell swoop
1. Implement something like https://github.com/facebook/react/pull/9187 using `prettier --list-different` on CI to prevent any un-`prettier`-ed code from being committed

**Comment by davidcornu** [comment]
^ once that's done people can update their editor configs or pre-commit hooks to suit their workflows.

**Comment by kaelig** [comment]
As discussed with @lemonmade over Slack, I'd like to do a spike on this and see how far I go towards seamless integration of prettier in our current process. As someone who's just joined I feel like this could be super useful to other new developers so worth investigating.

cc @dfmcphee

**Comment by clauderic** [comment]
+1 for this, I think this would be a great leap towards a more consistent codebase, especially if implemented at the CI level and as a pre-commit hook.

As far as pre-commit hooks go, a lot of large-scale projects nowadays are using a combination of [husky](https://github.com/typicode/husky) and [lint-staged](https://github.com/okonet/lint-staged) to make them easily shareable across the team without needing to be manually installed and to make sure to only run against staged files so they run faster. You can check out the [babel package.json](https://github.com/babel/babel/blob/7.0/package.json#L65-L70) for an example of how that works in practice.

**Comment by kaelig** [comment]
Thanks for the pointers. I was initially thinking we could encourage developers to install a Prettier extension in their text editor, but I guess pre-commit hooks scale much better!

I haven't had experience with modifying code at the CI level. Would that be something developers are comfortable with?

**Comment by GoodForOneFare** [comment]
Please check with #dev-accel before adding prehooks.  Last time I discussed that, they had a strong preference for finding alternatives.

**Comment by kaelig** [comment]
That's good to know! I'll make sure to have this in mind and will chat in case hooks seem like the best solution.

**Comment by kaelig** [comment]
Closing as we are now leveraging prettier!
