### ISSUE TITLE
Look into adding/ integrating other ESLint plugins

### ISSUE THREAD

**Issue by lemonmade** [Shopify/javascript#38]
Some good ones that might be relevant to us:

- [x] https://www.npmjs.com/package/eslint-plugin-chai-expect
- [x] https://www.npmjs.com/package/eslint-plugin-promise
- [x] https://www.npmjs.com/package/eslint-plugin-mocha
- [x] https://www.npmjs.com/package/eslint-plugin-jsx-a11y
- [x] https://www.npmjs.com/package/eslint-plugin-wpcalypso
- [x] https://www.npmjs.com/package/eslint-plugin-ava
- [x] https://www.npmjs.com/package/eslint-plugin-node
- [x] https://www.npmjs.com/package/eslint-plugin-flowtype

**Comment by ihsw** [comment]
Here is an awesome list.

https://github.com/dustinspecker/awesome-eslint

**Comment by lemonmade** [comment]
Thanks @ihsw! Hadn't seen that repo, and didn't know about some of those plugins. Will take a look!
