### ISSUE TITLE
Multiple `flash.coffee` files break global-reference-to-import transform

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#58]
If legacy + refactored versions of a file exist, the `global-reference-to-import-transform` bails.

```
Found multiple definitions for Shopify.Flash: 
admin/lib/flash.coffee:9:1:Shopify.Flash = Flash =
theme_editor/lib/flash.coffee:9:1:Shopify.Flash = Flash =
theme_editor_next/lib/flash.coffee:9:1:Shopify.Flash = Flash =
```

Per @lemonmade, we can probably ignore the `theme_editor` files and just notify the team that it's something they'll have to address before they run their code through esify.

**Comment by owilliams** [comment]
👍 We have plans to nuking the theme editor only version of flash.coffee.
