### ISSUE TITLE
Esify should not delete sprocket directives

### ISSUE THREAD

**Issue by fandy** [Shopify/javascript#70]
Manifest files are being ignored by Esify.

**Steps to reproduce:**

1. `esify app/assets/javascripts/admin/admin_vendors.coffee`
2. See `app/assets/javascripts/admin/admin_vendors.js`

`admin_vendors.js` is empty because `admin_vendors.coffee` is commented. Decaf treats it as an empty file and thus isn't compiling it.

**Main culprits**
- `app/assets/javascripts/admin/admin_vendors.coffee`
- `app/assets/javascripts/admin/merchant_checkout.coffee`

cc @lemonmade

**Comment by lemonmade** [comment]
Good catch. I've manually converted these files in this PR: https://github.com/Shopify/shopify/pull/71460, so I think that should resolve this issue.

**Comment by bouk** [comment]
@fandy this is unfortunately a limitation of decafjs https://github.com/juliankrispel/decaf/issues/1
