### ISSUE TITLE
Remove returns from named event handler functions

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#78]
If a function is defined and *only ever used as an `addEventListener`/`removeEventListener` parameter*, it's safe to remove any redundant returns from the function.

As a reference point, here's a **very** simplified version of the transformed `design_mode_next/buttons.js`:
```
function onMouseOver(event) {
  renderSectionButtons(section);
  return; // REMOVE THIS.
}

function enable() {
   document.addEventListener('mouseover', onMouseOver, true);
}
```

**Comment by lemonmade** [comment]
Do we have many of these? I feel like we do it a lot with passing methods as event listeners `document.addEventListener('click', this.handleClick, true)`, but that's going to be tougher to track correctly.

**Comment by GoodForOneFare** [comment]
Yeah :(  By my rough count, there's maybe 11 instances of this problem.  Probably fewer.  I thought this'd be a gentle intro to tackling the `this.handleClick` version, but it's maybe not worth the effort.

**Comment by fandy** [comment]
I think [function declarations are counterintuitive if they're only used once](https://www.youtube.com/watch?v=Bks59AaHe1c). What about a transform that replaces all single-use functions with inline functions?

**Comment by GoodForOneFare** [comment]
@fandy That's an interesting point.  Most of these functions are referenced twice: in `addEventListener`, then in `removeEventListener`.  I've updated the issue description to reflect this.

**Comment by fandy** [comment]
Closed until this becomes a problem
