### ISSUE TITLE
Remove hanging `return void 0` from if alternates

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#82]
The decaf process generates 54 functions that end with a pointless `else` block:
```
foo = () => {
  if (bar != null) {
    return bar(true);
  } else { // REMOVE THIS ELSE.
    return void 0;
  }
}
```
These should be removed.

**Comment by GoodForOneFare** [comment]
Note that decaf also generates similar non-returning consequents that *may* be cleaned up as part of this transform (or raise a separate issue if another transform is a better idea):
```
  _doRequest() {
    let ref;

    if ((ref = this.operation) != null) {
      ref.abort();
    } else { // DELETE THIS ELSE.
      void 0;
    }

    this.operation = $.ajax({
      url: this.url,
    });
  }
```

**Comment by lemonmade** [comment]
I don't understand when CoffeeScript/ decaf decides to process things into conditional blocks versus ternaries :( I think these are probably separate transforms, but we can leave it as a single issue.

**Comment by fandy** [comment]
Fixed in https://github.com/Shopify/javascript/pull/91
