### ISSUE TITLE
Verify shared instance properties -> class properties

### ISSUE THREAD

**Issue by lemonmade** [Shopify/javascript#84]
Noted in the second example of this issue: https://github.com/juliankrispel/decaf/issues/127.

Currently, we are translating this:

```coffee
class Foo
  bar: 123
```

to this:

```js
class Foo {
  bar = 123;
}
```

But these have different semantics: the CoffeeScript one goes on the prototype (shared between all instances) where the JavaScript one goes on the instance.

**Comment by GoodForOneFare** [comment]
@lemonmade this is another one that'll now throw an error during `decaf`.

**Comment by lemonmade** [comment]
What do you think the automated fix should look like? Should we add a `Foo.prototype.bar = 123` to decaf?

**Comment by GoodForOneFare** [comment]
Assuming that we split all classes into separate files (#125), I *think* we can insert any private stuff before the class definition.  So:

```coffeescript
class Shopify.AutocompleteV2
  LIST_CLASS = '.js-autocomplete-suggestions'
  PIXELS_FROM_BOTTOM_TO_INFINITE_SCROLL = 500
  ERROR_DISPLAY_TIME = 5000

  constructor: (node, @renderer, @options={}) ->
```

becomes
```js
const LIST_CLASS = '.js-autocomplete-suggestions'
const PIXELS_FROM_BOTTOM_TO_INFINITE_SCROLL = 500
const ERROR_DISPLAY_TIME = 5000

class Shopify.AutocompleteV2
  constructor: (node, @renderer, @options={}) ->
```

**Comment by GoodForOneFare** [comment]
Heh.  Yeah, prettymuch what you just raised in #157 :)

**Comment by lemonmade** [comment]
👍

**Comment by lemonmade** [comment]
Welp, I think the different issues are getting mixed up :P I think we are on the same page and https://github.com/Shopify/javascript/issues/138 partially covers what we are after in terms of shared literal properties.

**Comment by GoodForOneFare** [comment]
The mainline merge picked up a fix from Julian for this (https://github.com/shopify/decaf/blame/master/test/test.js#L1209).  Closing.
