### ISSUE TITLE
Make `global-reference-to-import` faster

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#95]
Based on a facile profile of transforms, `global-reference-to-import` accounts for ~60% of `esify`'s runtime.  

Most likely, this is caused by continually searching the codebase with `ag`/`ack`.  Adding a cache may significantly speed this up.

-----

Timing based on a full transform of `shopify/shopify/**/*.coffee`, with `ag`.

| Transform | Time (minutes) |
|----------------|----------------------|
| shopify-codemod/global-reference-to-import | 11.65 |
| js-codemod/no-vars | 1.54 |
| shopify-codemod/mocha-context-to-closure | 0.35 |
| shopify-codemod/global-identifier-to-import | 0.34 |
| shopify-codemod/coffeescript-soak-to-condition | 0.32 |
| shopify-codemod/function-to-arrow | 0.32 |
| shopify-codemod/remove-useless-return-from-test | 0.31 |
| shopify-codemod/ternary-statement-to-if-statement | 0.31 |
| js-codemod/unquote-properties | 0.27 |
| shopify-codemod/coffeescript-range-output-to-helper | 0.27 |
| shopify-codemod/conditional-assign-to-if-statement | 0.27 |
| shopify-codemod/remove-addeventlistener-returns | 0.27 |
| shopify-codemod/constant-function-expression-to-statement | 0.26 |
| js-codemod/template-literals | 0.25 |
| shopify-codemod/strip-template-literal-parenthesis | 0.25 |
| shopify-codemod/remove-trailing-else-undefined-return | 0.25 |
| js-codemod/object-shorthand | 0.25 |
| shopify-codemod/remove-empty-returns | 0.24 |
| shopify-codemod/mocha-context-to-global-reference | 0.17 |
| shopify-codemod/global-assignment-to-default-export | 0.16 |
| js-codemod/arrow-function | 0.14 |
| shopify-codemod/assert/call-count-equals-to-assert-called | 0.14 |
| shopify-codemod/assert/called-method-to-assert-called | 0.13 |
| shopify-codemod/assert/move-literals-to-expected-argument | 0.12 |
| shopify-codemod/assert/called-with-methods-to-assert-called-with | 0.12 |
| shopify-codemod/assert/negated-assert-ok-to-assert-not-ok | 0.12 |
| shopify-codemod/assert/assert-to-assert-ok | 0.12 |
| shopify-codemod/assert/assert-false-to-assert-fail | 0.12 |
| shopify-codemod/assert/called-equals-boolean-to-assert-called | 0.12 |
| shopify-codemod/assert/equality-comparisons-to-assertions | 0.12 |
| shopify-codemod/assert/falsy-called-method-to-assert-not-called | 0.11 |

**Comment by bouk** [comment]
Honestly, I thought about this and think we shouldn't care. It's a one time transform, and even if we do it 500 times it won't make sense to spend 2 hours trying to make it faster

**Comment by GoodForOneFare** [comment]
I've experienced the full transform many times over, and it makes sense to make it faster.  Sadly, our transforms aren't perfect, and regularly 🎩 the full output uncovers serious bugs.

**Comment by bouk** [comment]
I see. It could be made faster by doing a single pass over all the files and keeping track of what every file contains, but unless we do that in parallel it's not going to be faster, and tuning it might be quite an undertaking
