### ISSUE TITLE
Class property definitions should not disappear

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#96]
```coffeescript
class Shopify.AutocompleteV2
  LIST_CLASS = '.js-autocomplete-suggestions'
  PIXELS_FROM_BOTTOM_TO_INFINITE_SCROLL = 500
  ERROR_DISPLAY_TIME = 5000
```

```js
export default class AutocompleteV2 {
  constructor(node, renderer, options = {}) {
```

**Comment by GoodForOneFare** [comment]
Quick run through with `decaf` suggests that it's the source of the problem.

**Comment by GoodForOneFare** [comment]
An especially bad case of this is `SingleSelectResourcePicker`:
- In CoffeeScript, a `resourceSelected` class property is defined.
- In JavaScript, the class property is missing, and individual methods declare it as a `const`

**Comment by lemonmade** [comment]
Ugh, yeah, this is a terrible one because it has no direct parallel in ES6. Best pet is probably just making these static properties.

**Comment by GoodForOneFare** [comment]
Possibly fixed by mainline decaf merge.  Please don't start work on this until we've finished evaluation.

**Comment by GoodForOneFare** [comment]
Still a problem after the mainline merge :/  This is odd because it definitely fixed some class property issues.

**Comment by GoodForOneFare** [comment]
Duped by #157.
