### ISSUE TITLE
Simplify ?= operator transform output

### ISSUE THREAD

**Issue by GoodForOneFare** [Shopify/javascript#98]
`resource_browser.coffee` contains:
```coffeescript
    parentState.__id ?= _.uniqueId()
```

Which becomes the rather verbose:
```js
    if (parentState.__id != null) {
      parentState.__id;
    } else {
      parentState.__id = _.uniqueId();
    }
```

**Comment by GoodForOneFare** [comment]
Still an issue after merging in mainline decaf.  My preference would be to fix it in decaf, but a transform is okay, too.

**Comment by lemonmade** [comment]
Do you know how hard it would be to do this in decaf?

**Comment by GoodForOneFare** [comment]
I take back my decaf preference.  It isn't behaving too badly here, and has to handle edge cases like return-existential-assignment.  Tweaking/adding a transforms would be quicker/easier.

With only decaf running, this Coffee:
```coffeescript
opt["$field"] ?= @element
```

becomes
```js
(opt['$field'] != null ? opt['$field'] : opt['$field'] = this.element);
```

A transform should be able to examine consequents and rewrite if they contain only `Identifier`s/`MemberExpression`s.

**Comment by lemonmade** [comment]
👍 codemod it is!

**Comment by lemonmade** [comment]
@justinthec want to take a crack at this transform next?

**Comment by GoodForOneFare** [comment]
Verified that this is still a problem.
